version: 0.2
phases:
  build:
    commands:
      - cd sample_page
      - npm install
      - npm run build
  post_build:
    commands:
      - aws s3 cp dist/ s3://msa-app-front-page-sample --recursive
