// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_appsync_graphqlEndpoint": "https://6avo22gr7zau3lpr7tfldoam6m.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-yye43u67kzdzplensmjwtpltoi",
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:10cb71cd-624f-42eb-a26c-aaa40934e6f3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_74k7JrgGn",
    "aws_user_pools_web_client_id": "25hsfgbo2f1qvjgbp1bo888fvv"
};


export default awsmobile;
